wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655276443
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      4: 3.9.12
      5: 0.12.18
      8:
      - 5
batch_size:
  desc: null
  value: 38
dense:
  desc: null
  value: 636
dropout:
  desc: null
  value: 0.7531062436991232
epochs:
  desc: null
  value: 337
learning_rate:
  desc: null
  value: 0.01
optimizer:
  desc: null
  value: rmsprop
