wandb_version: 1

activation:
  value: relu
batch_size:
  value: 20
dense:
  value: 1024
dropout:
  value: 0.2
learning_rate:
  value: 3.0e-05
optimizer:
  value: rmsprop
pretrain_net:
  value: resnet
