wandb_version: 1

activation:
  value: relu
batch_size:
  value: 20
dense:
  value: 1024
dropout:
  value: 0.5
learning_rate:
  value: 0.0001
optimizer:
  value: adam
pretrain_net:
  value: inception
