wandb_version: 1

activation:
  value: elu
batch_size:
  value: 20
dense:
  value: 1024
dropout:
  value: 0.2
learning_rate:
  value: 0.001
optimizer:
  value: rmsprop
pretrain_net:
  value: inception
