wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655267747
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      4: 3.9.12
      5: 0.12.18
      8:
      - 5
batch_size:
  desc: null
  value: 141
dense:
  desc: null
  value: 1553
drop_out:
  desc: null
  value: 0.5031734673682338
dropout:
  desc: null
  value: 0.9375576097037508
epoch:
  desc: null
  value: 10
epochs:
  desc: null
  value: 40
learning_rate:
  desc: null
  value: 0.0011126380079176847
optimizer:
  desc: null
  value: adam
