wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1655276086
    t:
      1:
      - 3
      - 5
      - 53
      - 55
      2:
      - 3
      - 5
      - 53
      - 55
      4: 3.9.12
      5: 0.12.18
      8:
      - 5
batch_size:
  desc: null
  value: 33
dense:
  desc: null
  value: 1025
dropout:
  desc: null
  value: 0.3660359051546559
epochs:
  desc: null
  value: 918
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: adam
