wandb_version: 1

activation:
  value: softmax
batch_size:
  value: 50
dense:
  value: 32
dropout:
  value: 0.5
learning_rate:
  value: 0.0001
optimizer:
  value: adam
pretrain_net:
  value: inception
